### PR TITLE
Attach winbox instance to element and make callback functions accessible and editable after initialization

### PR DESCRIPTION
**Pull request by kodie**
This PR takes care of #61 and #75.

With this PR, the `winbox` instance is attached to the element and can be used like so:

```js
var myModal = document.getElementById('my-modal')

myModal.winbox.hide()

myModal.winbox.onclose = function (force) {
  alert('Hey, check this out, I changed the onclose callback function!')
}
```

### CODE REVIEW

**Comment by Ademking** [comment]
@ts-thomas 
image


image

I'm using the latest version and i'm getting "Cannot read properties of undefined"

**Comment by kodie** [comment]
@Ademking This feature has been merged in but hasn't been compiled or released yet. In order to use it you'll have to clone this repo and then run `composer run build` and the files in the `dist` directory will be updated.

**Comment by Ademking** [comment]
@kodie Thank you so much

**Comment by Ademking** [comment]
> @Ademking This feature has been merged in but hasn't been compiled or released yet. In order to use it you'll have to clone this repo and then run `composer run build` and the files in the `dist` directory will be updated.

You mean `npm run build`  ?

**Pull request merged**
