### PR TITLE
make onclose event cancelable

### PR DESCRIPTION
**Pull request by itgoldman**
by returning true from `onclose` user supplied event, you can prevent close from occurring.
example
```js
var foo_are_you_sure = function () {
    var sure = window.confirm("are you sure to close window?")
    if (!sure) {
        return true;
    }
}

new WinBox("Theme: Modern", {
    onclose: foo_are_you_sure
});
```
also, method `close` now supports option to force close without firing user supplied `onclose`.

### CODE REVIEW

**Comment by ts-thomas** [comment]
Hello, thanks a lot for the contribution. There is an issue with your pull request. You have committed a lot of code style changes which was automatically applied by your editor auto style configuration. Please consider to just commit the changes you want to take. I would like to keep your name in the commit history, so I will merge your PR and apply the code style changes back, to keep the history clean.

**Comment by itgoldman** [comment]
Hi , thanks for the merge. I will try to keep the style next time.

**Comment by ts-thomas** [comment]
I made some little changes in how to apply "force" state. This flag is now delegated to the assigned callback handler as a first parameter. This way the user is also able to apply additional logic when force closing a window. 

https://github.com/nextapps-de/winbox#callbacks

**Comment by itgoldman** [comment]
Please allow me to note that there are 2 non related additions:
1. cancelable onclose -> which is fine
2. "force" close parameter or state -> which is a dubious design decision.
because it is up to the onclose callback to decide if the window shall
close or not anyway.

**Review by MohdWaseem0 — APPROVED** [review]

**Pull request merged**
